@startuml authenticaion

actor 사용자 as USER
left to right direction

rectangle Authentication {
    usecase "Create Account" as AUTH_CREATE
    usecase "Delete Account" as AUTH_DELETE

    usecase "Sign in" as AUTH_SIGN_IN
    usecase "Sign out" as AUTH_SIGN_OUT

    usecase "Find Account" as AUTH_FIND
    usecase "Find ID" as AUTH_FIND_ID
    usecase "Find PWD" as AUTH_FIND_PWD

    USER --> AUTH_CREATE
    USER --> AUTH_DELETE
    USER --> AUTH_FIND

    AUTH_FIND_ID ..up..> AUTH_FIND
    AUTH_FIND_PWD ..up..> AUTH_FIND

    USER --> AUTH_SIGN_IN
    USER --> AUTH_SIGN_OUT
}

@enduml